/**
 * Deterministic, per-algorithm, per-language line map for the visualizer's code-sync
 * highlighting (CodeSyncPanel.jsx). Replaces the old approach of a handful of shared,
 * category-wide {keyword: lineNumber} tables reused across every algorithm regardless
 * of language — which is what caused the highlighted line to frequently land on an
 * unrelated comment or the wrong line entirely (see NEXT_PHASE_QA_REPORT.md).
 *
 * Each entry is an ORDERED list of { test, lines } — `test` is a RegExp matched against
 * the live step's `description` text (case-insensitive), and `lines` gives the 1-based
 * line number to highlight in each language's real source (shared/algorithms/codeSync/
 * algorithmSources.js) or pseudocode (templates.js), for THIS SPECIFIC algorithm. The
 * first matching pattern wins. This file was generated by cross-referencing the exact
 * step description strings emitted by shared/algorithms/{searching,sorting,graphs,trees,
 * structures,dp}.js against the real source text authored in algorithmSources.js/
 * templates.js — regenerate via the same process (see NEXT_PHASE_QA_REPORT.md) if either
 * side changes.
 */

export const LINE_MAP = {
  "linear-search": [
    { test: /search for/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":4,"cpp":4,"java":3} },
    { test: /check index/i, lines: {"pseudocode":2,"python":5,"javascript":5,"c":7,"cpp":7,"java":6} },
    { test: /found at index/i, lines: {"pseudocode":7,"python":7,"javascript":7,"c":9,"cpp":9,"java":8} },
    { test: /not found/i, lines: {"pseudocode":7,"python":9,"javascript":11,"c":13,"cpp":13,"java":12} },
  ],
  "binary-search": [
    { test: /binary search for/i, lines: {"pseudocode":1,"python":3,"javascript":3,"c":3,"cpp":3,"java":4} },
    { test: /inspect middle/i, lines: {"pseudocode":1,"python":6,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /found at index/i, lines: {"pseudocode":1,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
    { test: /right half/i, lines: {"pseudocode":1,"python":11,"javascript":10,"c":10,"cpp":10,"java":11} },
    { test: /left half/i, lines: {"pseudocode":1,"python":14,"javascript":12,"c":12,"cpp":12,"java":13} },
    { test: /not found/i, lines: {"pseudocode":1,"python":17,"javascript":15,"c":15,"cpp":15,"java":16} },
  ],
  "jump-search": [
    { test: /jump search for/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /jump to index/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":5,"cpp":6,"java":7} },
    { test: /linear scan index/i, lines: {"pseudocode":6,"python":12,"javascript":12,"c":11,"cpp":12,"java":13} },
    { test: /found at index/i, lines: {"pseudocode":6,"python":14,"javascript":14,"c":13,"cpp":14,"java":15} },
    { test: /not found/i, lines: {"pseudocode":10,"python":11,"javascript":10,"c":9,"cpp":10,"java":11} },
  ],
  "interpolation-search": [
    { test: /interpolation search for/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /single element check/i, lines: {"pseudocode":6,"python":5,"javascript":5,"c":5,"cpp":5,"java":6} },
    { test: /probe index/i, lines: {"pseudocode":6,"python":5,"javascript":5,"c":5,"cpp":5,"java":6} },
    { test: /found at index/i, lines: {"pseudocode":6,"python":7,"javascript":7,"c":7,"cpp":7,"java":8} },
    { test: /not found/i, lines: {"pseudocode":11,"python":14,"javascript":12,"c":12,"cpp":12,"java":13} },
  ],
  "ternary-search": [
    { test: /ternary search for/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /check first third/i, lines: {"pseudocode":9,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
    { test: /check second third/i, lines: {"pseudocode":9,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
    { test: /found at index/i, lines: {"pseudocode":9,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
    { test: /first third/i, lines: {"pseudocode":12,"python":13,"javascript":11,"c":11,"cpp":11,"java":12} },
    { test: /third third/i, lines: {"pseudocode":12,"python":13,"javascript":11,"c":11,"cpp":11,"java":12} },
    { test: /middle third/i, lines: {"pseudocode":12,"python":13,"javascript":11,"c":11,"cpp":11,"java":12} },
    { test: /not found/i, lines: {"pseudocode":16,"python":20,"javascript":16,"c":16,"cpp":16,"java":17} },
  ],
  "exponential-search": [
    { test: /exponential search for/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /starting bound/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /double range/i, lines: {"pseudocode":4,"python":5,"javascript":4,"c":4,"cpp":4,"java":5} },
    { test: /binary search within range/i, lines: {"pseudocode":10,"python":10,"javascript":8,"c":8,"cpp":9,"java":9} },
    { test: /inspect middle/i, lines: {"pseudocode":10,"python":10,"javascript":8,"c":8,"cpp":9,"java":9} },
    { test: /found at index/i, lines: {"pseudocode":10,"python":13,"javascript":11,"c":11,"cpp":12,"java":12} },
    { test: /right half/i, lines: {"pseudocode":14,"python":16,"javascript":12,"c":12,"cpp":13,"java":13} },
    { test: /left half/i, lines: {"pseudocode":15,"python":18,"javascript":13,"c":13,"cpp":14,"java":14} },
    { test: /not found/i, lines: {"pseudocode":16,"python":19,"javascript":15,"c":15,"cpp":16,"java":16} },
  ],
  "bubble-sort": [
    { test: /starting bubble sort/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /compare/i, lines: {"pseudocode":2,"python":6,"javascript":6,"c":5,"cpp":6,"java":7} },
    { test: /swap/i, lines: {"pseudocode":2,"python":8,"javascript":8,"c":7,"cpp":8,"java":9} },
    { test: /final position/i, lines: {"pseudocode":2,"python":4,"javascript":4,"c":3,"cpp":4,"java":5} },
    { test: /complete/i, lines: {"pseudocode":2,"python":4,"javascript":14,"c":3,"cpp":4,"java":5} },
  ],
  "selection-sort": [
    { test: /starting selection sort/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /compare .* current minimum/i, lines: {"pseudocode":2,"python":6,"javascript":6,"c":5,"cpp":6,"java":7} },
    { test: /place minimum/i, lines: {"pseudocode":2,"python":10,"javascript":10,"c":9,"cpp":10,"java":11} },
  ],
  "insertion-sort": [
    { test: /starting insertion sort/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /insert .* into sorted portion/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /compare .* with key/i, lines: {"pseudocode":2,"python":6,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /shift/i, lines: {"pseudocode":2,"python":6,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /place key/i, lines: {"pseudocode":2,"python":10,"javascript":11,"c":11,"cpp":11,"java":12} },
  ],
  "merge-sort": [
    { test: /starting merge sort/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
    { test: /merge subarrays/i, lines: {"pseudocode":1,"python":1,"javascript":1,"c":1,"cpp":1,"java":1} },
    { test: /compare/i, lines: {"pseudocode":10,"python":1,"javascript":1,"c":1,"cpp":1,"java":1} },
    { test: /merged segment/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
  ],
  "quick-sort": [
    { test: /starting quick sort/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
    { test: /choose pivot/i, lines: {"pseudocode":4,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
    { test: /compare .* with pivot/i, lines: {"pseudocode":5,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
    { test: /move smaller/i, lines: {"pseudocode":5,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
    { test: /place pivot/i, lines: {"pseudocode":5,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
  ],
  "heap-sort": [
    { test: /build max heap/i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":3,"cpp":4,"java":5} },
    { test: /compare left child/i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":3,"cpp":4,"java":5} },
    { test: /compare right child/i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":3,"cpp":4,"java":5} },
    { test: /swap to maintain heap/i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":3,"cpp":4,"java":5} },
    { test: /extract max/i, lines: {"pseudocode":4,"python":8,"javascript":7,"c":6,"cpp":7,"java":8} },
  ],
  "counting-sort": [
    { test: /starting counting sort/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /frequency array/i, lines: {"pseudocode":1,"python":1,"javascript":1,"c":1,"cpp":1,"java":1} },
    { test: /place .* in output/i, lines: {"pseudocode":9,"python":12,"javascript":10,"c":10,"cpp":11,"java":10} },
  ],
  "radix-sort": [
    { test: /starting radix sort/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /sorted by digit place/i, lines: {"pseudocode":5,"python":5,"javascript":5,"c":5,"cpp":4,"java":5} },
  ],
  "bucket-sort": [
    { test: /starting bucket sort/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /place .* into bucket/i, lines: {"pseudocode":4,"python":5,"javascript":5,"c":4,"cpp":4,"java":6} },
    { test: /sort bucket/i, lines: {"pseudocode":8,"python":10,"javascript":11,"c":10,"cpp":10,"java":9} },
  ],
  "shell-sort": [
    { test: /starting shell sort/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /use gap size/i, lines: {"pseudocode":5,"python":6,"javascript":5,"c":4,"cpp":5,"java":6} },
    { test: /compare .* with .* at gap/i, lines: {"pseudocode":9,"python":10,"javascript":9,"c":8,"cpp":9,"java":10} },
    { test: /insert .* at index/i, lines: {"pseudocode":9,"python":10,"javascript":9,"c":8,"cpp":9,"java":10} },
  ],
  "tim-sort": [
    { test: /starting tim sort/i, lines: {"pseudocode":2,"python":3,"javascript":3,"c":3,"cpp":3,"java":4} },
    { test: /run .* sorted by insertion sort/i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":4,"cpp":5,"java":6} },
    { test: /merge runs/i, lines: {"pseudocode":1,"python":8,"javascript":9,"c":9,"cpp":9,"java":10} },
  ],
  "dfs": [
    { test: /start dfs/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":7,"cpp":1,"java":1} },
    { test: /visit node/i, lines: {"pseudocode":2,"python":6,"javascript":6,"c":7,"cpp":1,"java":1} },
    { test: /push neighbor/i, lines: {"pseudocode":10,"python":12,"javascript":6,"c":7,"cpp":1,"java":1} },
    { test: /complete/i, lines: {"pseudocode":13,"python":15,"javascript":15,"c":7,"cpp":1,"java":1} },
  ],
  "bfs": [
    { test: /start bfs/i, lines: {"pseudocode":2,"python":4,"javascript":2,"c":2,"cpp":1,"java":1} },
    { test: /visit node/i, lines: {"pseudocode":7,"python":8,"javascript":6,"c":6,"cpp":5,"java":7} },
    { test: /enqueue neighbor/i, lines: {"pseudocode":9,"python":11,"javascript":6,"c":6,"cpp":5,"java":7} },
    { test: /complete/i, lines: {"pseudocode":13,"python":15,"javascript":16,"c":6,"cpp":5,"java":7} },
  ],
  "dijkstra": [
    { test: /initialize distances/i, lines: {"pseudocode":3,"python":5,"javascript":3,"c":3,"cpp":3,"java":4} },
    { test: /select node/i, lines: {"pseudocode":7,"python":10,"javascript":9,"c":3,"cpp":10,"java":10} },
    { test: /relax edge/i, lines: {"pseudocode":10,"python":14,"javascript":13,"c":3,"cpp":14,"java":14} },
    { test: /complete/i, lines: {"pseudocode":13,"python":18,"javascript":20,"c":3,"cpp":17,"java":18} },
  ],
  "bellman-ford": [
    { test: /initialize bellman-ford/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /relax .* pass/i, lines: {"pseudocode":7,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
    { test: /complete/i, lines: {"pseudocode":10,"python":11,"javascript":12,"c":8,"cpp":12,"java":13} },
  ],
  "floyd-warshall": [
    { test: /initialize distance matrix/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /relax path/i, lines: {"pseudocode":8,"python":7,"javascript":7,"c":7,"cpp":7,"java":8} },
    { test: /complete/i, lines: {"pseudocode":11,"python":10,"javascript":12,"c":7,"cpp":7,"java":8} },
  ],
  "prim": [
    { test: /start prim's mst/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /add edge/i, lines: {"pseudocode":7,"python":7,"javascript":7,"c":8,"cpp":8,"java":9} },
    { test: /complete/i, lines: {"pseudocode":11,"python":11,"javascript":12,"c":8,"cpp":13,"java":14} },
  ],
  "kruskal": [
    { test: /sort edges/i, lines: {"pseudocode":3,"python":3,"javascript":3,"c":3,"cpp":3,"java":4} },
    { test: /add edge/i, lines: {"pseudocode":8,"python":8,"javascript":8,"c":9,"cpp":9,"java":10} },
    { test: /skip edge/i, lines: {"pseudocode":8,"python":8,"javascript":8,"c":9,"cpp":9,"java":10} },
    { test: /complete/i, lines: {"pseudocode":12,"python":12,"javascript":14,"c":9,"cpp":15,"java":16} },
  ],
  "a-star": [
    { test: /a\* search from/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":1,"cpp":2,"java":3} },
    { test: /expand node/i, lines: {"pseudocode":4,"python":6,"javascript":6,"c":5,"cpp":7,"java":7} },
    { test: /goal .* reached/i, lines: {"pseudocode":7,"python":9,"javascript":9,"c":8,"cpp":12,"java":10} },
    { test: /update path to/i, lines: {"pseudocode":9,"python":12,"javascript":11,"c":10,"cpp":14,"java":12} },
    { test: /could not reach goal/i, lines: {"pseudocode":9,"python":19,"javascript":21,"c":13,"cpp":17,"java":15} },
  ],
  "topological-sort": [
    { test: /compute in-degree/i, lines: {"pseudocode":1,"python":3,"javascript":3,"c":3,"cpp":3,"java":4} },
    { test: /remove node/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":6,"cpp":7,"java":8} },
    { test: /decrement in-degree/i, lines: {"pseudocode":10,"python":10,"javascript":10,"c":10,"cpp":11,"java":12} },
    { test: /topological order/i, lines: {"pseudocode":14,"python":15,"javascript":16,"c":10,"cpp":16,"java":17} },
  ],
  "union-find": [
    { test: /initialize each node/i, lines: {"pseudocode":9,"python":13,"javascript":13,"c":11,"cpp":11,"java":12} },
    { test: /union\(/i, lines: {"pseudocode":7,"python":9,"javascript":9,"c":8,"cpp":8,"java":9} },
    { test: /find\(.*==.*find/i, lines: {"pseudocode":7,"python":9,"javascript":9,"c":8,"cpp":8,"java":9} },
    { test: /complete/i, lines: {"pseudocode":9,"python":13,"javascript":13,"c":11,"cpp":11,"java":12} },
  ],
  "scc-kosaraju": [
    { test: /pass 1/i, lines: {"pseudocode":3,"python":5,"javascript":5,"c":5,"cpp":5,"java":6} },
    { test: /visit .* \(pass 1/i, lines: {"pseudocode":3,"python":5,"javascript":5,"c":5,"cpp":5,"java":6} },
    { test: /finish /i, lines: {"pseudocode":3,"python":5,"javascript":5,"c":5,"cpp":5,"java":6} },
    { test: /pass 2/i, lines: {"pseudocode":6,"python":12,"javascript":12,"c":10,"cpp":11,"java":12} },
    { test: /visit .* \(pass 2/i, lines: {"pseudocode":6,"python":12,"javascript":12,"c":10,"cpp":11,"java":12} },
    { test: /component \d+:/i, lines: {"pseudocode":6,"python":12,"javascript":12,"c":10,"cpp":11,"java":12} },
    { test: /strongly connected components:/i, lines: {"pseudocode":6,"python":18,"javascript":17,"c":10,"cpp":16,"java":17} },
  ],
  "bridges-tarjan": [
    { test: /discover .* at time/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
    { test: /back edge/i, lines: {"pseudocode":12,"python":20,"javascript":18,"c":13,"cpp":12,"java":14} },
    { test: /back from/i, lines: {"pseudocode":10,"python":16,"javascript":15,"c":10,"cpp":9,"java":11} },
    { test: /is a bridge/i, lines: {"pseudocode":10,"python":16,"javascript":15,"c":10,"cpp":9,"java":11} },
    { test: /bridges found/i, lines: {"pseudocode":14,"python":25,"javascript":24,"c":10,"cpp":9,"java":11} },
  ],
  "articulation-points": [
    { test: /discover .* at time/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
    { test: /is an articulation point \(child/i, lines: {"pseudocode":11,"python":18,"javascript":17,"c":12,"cpp":11,"java":12} },
    { test: /is an articulation point \(root/i, lines: {"pseudocode":11,"python":18,"javascript":17,"c":12,"cpp":11,"java":12} },
    { test: /articulation points:/i, lines: {"pseudocode":15,"python":29,"javascript":27,"c":12,"cpp":11,"java":12} },
  ],
  "bst-insert": [
    { test: /build binary search tree/i, lines: {"pseudocode":2,"python":6,"javascript":4,"c":1,"cpp":1,"java":5} },
    { test: /compare .* with/i, lines: {"pseudocode":2,"python":9,"javascript":7,"c":7,"cpp":7,"java":8} },
    { test: /tree after inserting/i, lines: {"pseudocode":11,"python":13,"javascript":11,"c":11,"cpp":11,"java":12} },
    { test: /construction complete/i, lines: {"pseudocode":11,"python":13,"javascript":11,"c":11,"cpp":11,"java":12} },
  ],
  "avl-insert": [
    { test: /compare .* with/i, lines: {"pseudocode":3,"python":3,"javascript":3,"c":3,"cpp":3,"java":4} },
    { test: /rotation/i, lines: {"pseudocode":9,"python":9,"javascript":9,"c":9,"cpp":9,"java":10} },
    { test: /avl tree after inserting/i, lines: {"pseudocode":7,"python":7,"javascript":7,"c":7,"cpp":7,"java":8} },
    { test: /construction complete/i, lines: {"pseudocode":9,"python":9,"javascript":9,"c":9,"cpp":9,"java":10} },
  ],
  "trie-insert": [
    { test: /build trie/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":1} },
    { test: /insert word/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":1} },
    { test: /add character/i, lines: {"pseudocode":5,"python":5,"javascript":5,"c":6,"cpp":5,"java":6} },
    { test: /mark end of word/i, lines: {"pseudocode":9,"python":9,"javascript":9,"c":10,"cpp":9,"java":10} },
    { test: /trie construction complete/i, lines: {"pseudocode":10,"python":10,"javascript":10,"c":11,"cpp":10,"java":11} },
  ],
  "heapify": [
    { test: /visualize array as binary heap/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /compare .* with left child/i, lines: {"pseudocode":6,"python":5,"javascript":5,"c":5,"cpp":5,"java":6} },
    { test: /compare .* with right child/i, lines: {"pseudocode":6,"python":5,"javascript":5,"c":5,"cpp":5,"java":6} },
    { test: /swap to restore heap property/i, lines: {"pseudocode":9,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
    { test: /heapify subtree/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /max heap ready/i, lines: {"pseudocode":2,"python":11,"javascript":11,"c":11,"cpp":11,"java":12} },
  ],
  "tree-inorder": [
    { test: /built binary search tree/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /visit .* \(inorder/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /traversal complete/i, lines: {"pseudocode":8,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
  ],
  "tree-preorder": [
    { test: /built binary search tree/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /visit .* \(preorder/i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":4,"cpp":4,"java":5} },
    { test: /traversal complete/i, lines: {"pseudocode":8,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
  ],
  "tree-postorder": [
    { test: /built binary search tree/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /visit .* \(postorder/i, lines: {"pseudocode":8,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
    { test: /traversal complete/i, lines: {"pseudocode":8,"python":8,"javascript":8,"c":8,"cpp":8,"java":9} },
  ],
  "level-order-bfs": [
    { test: /built binary search tree/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /dequeue and visit/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":6,"cpp":7,"java":8} },
    { test: /traversal complete/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":6,"cpp":7,"java":8} },
  ],
  "segment-tree-demo": [
    { test: /build segment tree/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /place leaf value/i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":3,"cpp":3,"java":4} },
    { test: /internal node/i, lines: {"pseudocode":6,"python":7,"javascript":6,"c":5,"cpp":5,"java":6} },
    { test: /range sum query/i, lines: {"pseudocode":9,"python":12,"javascript":11,"c":8,"cpp":8,"java":9} },
  ],
  "fenwick-tree-demo": [
    { test: /build fenwick tree/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /update\(index/i, lines: {"pseudocode":3,"python":3,"javascript":3,"c":3,"cpp":3,"java":4} },
    { test: /query\(prefix sum/i, lines: {"pseudocode":9,"python":10,"javascript":12,"c":8,"cpp":8,"java":9} },
  ],
  "stack-operations": [
    { test: /initialize empty stack/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /push /i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":4,"cpp":4,"java":5} },
    { test: /peek top element/i, lines: {"pseudocode":6,"python":7,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /pop from stack/i, lines: {"pseudocode":6,"python":7,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /complete/i, lines: {"pseudocode":10,"python":11,"javascript":11,"c":6,"cpp":6,"java":7} },
  ],
  "queue-operations": [
    { test: /initialize empty queue/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /enqueue /i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":4,"cpp":4,"java":5} },
    { test: /front element is/i, lines: {"pseudocode":6,"python":7,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /dequeue front element/i, lines: {"pseudocode":6,"python":7,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /complete/i, lines: {"pseudocode":10,"python":11,"javascript":11,"c":6,"cpp":6,"java":7} },
  ],
  "linked-list-insert": [
    { test: /start with empty linked list/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /insert .* at tail/i, lines: {"pseudocode":5,"python":6,"javascript":5,"c":5,"cpp":5,"java":6} },
    { test: /build complete/i, lines: {"pseudocode":9,"python":10,"javascript":8,"c":8,"cpp":8,"java":9} },
  ],
  "hash-linear-probing": [
    { test: /create hash table/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /hash /i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /collision at index/i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":4,"cpp":4,"java":5} },
    { test: /place .* at index/i, lines: {"pseudocode":7,"python":7,"javascript":8,"c":8,"cpp":8,"java":9} },
    { test: /insertion complete/i, lines: {"pseudocode":7,"python":7,"javascript":8,"c":8,"cpp":8,"java":9} },
  ],
  "monotonic-stack": [
    { test: /initialize empty monotonic/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /consider arr/i, lines: {"pseudocode":5,"python":5,"javascript":5,"c":5,"cpp":5,"java":7} },
    { test: /> arr\[.*\]: pop index/i, lines: {"pseudocode":5,"python":8,"javascript":8,"c":8,"cpp":8,"java":10} },
    { test: /push index/i, lines: {"pseudocode":5,"python":5,"javascript":5,"c":5,"cpp":5,"java":7} },
  ],
  "deque-sliding-window": [
    { test: /sliding window maximum with window size/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /process index/i, lines: {"pseudocode":8,"python":9,"javascript":8,"c":7,"cpp":8,"java":9} },
    { test: /window ending at/i, lines: {"pseudocode":8,"python":9,"javascript":8,"c":7,"cpp":8,"java":9} },
  ],
  "two-pointer": [
    { test: /initialize two pointers/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /compare arr\[/i, lines: {"pseudocode":5,"python":4,"javascript":4,"c":4,"cpp":4,"java":5} },
    { test: /move pointers inward/i, lines: {"pseudocode":5,"python":4,"javascript":4,"c":4,"cpp":4,"java":5} },
    { test: /complete/i, lines: {"pseudocode":11,"python":13,"javascript":11,"c":4,"cpp":11,"java":5} },
  ],
  "sliding-window": [
    { test: /array with window size/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /window \[/i, lines: {"pseudocode":7,"python":7,"javascript":7,"c":6,"cpp":6,"java":8} },
  ],
  "prefix-sum": [
    { test: /build prefix sum array/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /prefix\[/i, lines: {"pseudocode":5,"python":5,"javascript":5,"c":4,"cpp":5,"java":6} },
  ],
  "greedy-activity": [
    { test: /activities represented by finish time/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /sort activities by finish time/i, lines: {"pseudocode":2,"python":3,"javascript":3,"c":3,"cpp":3,"java":4} },
    { test: /select activity/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /skip activity/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":6,"cpp":6,"java":7} },
  ],
  "backtracking-subsets": [
    { test: /generate all subsets/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /include arr\[/i, lines: {"pseudocode":6,"python":6,"javascript":7,"c":7,"cpp":7,"java":8} },
    { test: /exclude arr\[/i, lines: {"pseudocode":10,"python":10,"javascript":11,"c":10,"cpp":11,"java":12} },
    { test: /complete subset/i, lines: {"pseudocode":10,"python":4,"javascript":11,"c":10,"cpp":4,"java":5} },
  ],
  "kmp-search": [
    { test: /kmp search for pattern/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /built failure function/i, lines: {"pseudocode":3,"python":3,"javascript":3,"c":3,"cpp":3,"java":4} },
    { test: /compare text\[/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":6,"cpp":7,"java":8} },
    { test: /full match found/i, lines: {"pseudocode":9,"python":11,"javascript":9,"c":9,"cpp":10,"java":11} },
    { test: /complete/i, lines: {"pseudocode":13,"python":15,"javascript":15,"c":9,"cpp":15,"java":16} },
  ],
  "rabin-karp": [
    { test: /rabin-karp search for pattern/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /window \[.*\] hash/i, lines: {"pseudocode":6,"python":7,"javascript":7,"c":7,"cpp":7,"java":8} },
    { test: /hash match confirmed/i, lines: {"pseudocode":6,"python":7,"javascript":7,"c":7,"cpp":7,"java":8} },
    { test: /complete/i, lines: {"pseudocode":11,"python":13,"javascript":16,"c":7,"cpp":16,"java":17} },
  ],
  "fibonacci-dp": [
    { test: /compute fib\(\d+\) with memoization/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /base case/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /memo hit/i, lines: {"pseudocode":4,"python":5,"javascript":4,"c":4,"cpp":4,"java":5} },
    { test: /compute fib\(\d+\) from subproblems/i, lines: {"pseudocode":6,"python":8,"javascript":6,"c":6,"cpp":6,"java":7} },
    { test: /fib\(\d+\) =/i, lines: {"pseudocode":6,"python":8,"javascript":6,"c":6,"cpp":6,"java":7} },
  ],
  "knapsack-dp": [
    { test: /knapsack dp table/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /dp\[/i, lines: {"pseudocode":6,"python":7,"javascript":7,"c":6,"cpp":7,"java":8} },
    { test: /max value/i, lines: {"pseudocode":6,"python":7,"javascript":7,"c":6,"cpp":7,"java":8} },
  ],
  "coin-change-dp": [
    { test: /coin change for amount/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /dp\[/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":7,"cpp":6,"java":8} },
    { test: /minimum coins for/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":7,"cpp":6,"java":8} },
  ],
  "lis-dp": [
    { test: /initialize lis lengths/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /lis ending at index/i, lines: {"pseudocode":6,"python":6,"javascript":6,"c":6,"cpp":6,"java":8} },
    { test: /lis length =/i, lines: {"pseudocode":8,"python":9,"javascript":10,"c":6,"cpp":10,"java":8} },
  ],
  "bitmask-dp": [
    { test: /bitmask dp: track achievable subset sums/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":1,"cpp":1,"java":1} },
    { test: /dp \|= dp << /i, lines: {"pseudocode":4,"python":4,"javascript":4,"c":4,"cpp":4,"java":5} },
  ],
  "edit-distance-dp": [
    { test: /edit distance dp table/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":3} },
    { test: /==.*dp\[i\]\[j\] = dp\[i - 1\]\[j - 1\]/i, lines: {"pseudocode":2,"python":2,"javascript":2,"c":2,"cpp":2,"java":10} },
    { test: /!=.*dp\[i\]\[j\] = 1 \+ min/i, lines: {"pseudocode":9,"python":12,"javascript":12,"c":12,"cpp":12,"java":13} },
  ],
};

/**
 * Resolves the code line to highlight for a given step. Tries the algorithm's own
 * LINE_MAP patterns first (accurate, hand-verified against real source); falls back to
 * a step-index-based cycle only for an algorithm with no LINE_MAP entry at all (should
 * not happen for any algorithm in the catalog — this is a defensive last resort).
 */
export const inferCodeLine = (algorithmId, category, description, stepIndex, totalSteps, language = 'python') => {
  const patterns = LINE_MAP[algorithmId];
  if (patterns) {
    const text = description ?? '';
    for (const p of patterns) {
      if (p.test.test(text)) {
        return p.lines[language] ?? p.lines.pseudocode ?? 1;
      }
    }
    // No pattern matched this description — stay near the last pattern's line for this
    // language rather than jumping to an arbitrary fallback.
    const last = patterns[patterns.length - 1];
    if (last) return last.lines[language] ?? last.lines.pseudocode ?? 1;
  }

  if (stepIndex === 0) return 1;
  if (stepIndex === totalSteps - 1) return 10;
  return Math.min(2 + (stepIndex % 7), 9);
};

export const enrichStepsWithCodeSync = (algorithmId, category, steps, language = 'python') => {
  const total = steps.length;
  return steps.map((step, index) => ({
    ...step,
    codeLine: step.codeLine ?? inferCodeLine(algorithmId, category, step.description, index, total, language),
  }));
};

export default { inferCodeLine, enrichStepsWithCodeSync, LINE_MAP };
