import * as sorting from './sorting.js';
import * as searching from './searching.js';
import * as trees from './trees.js';
import * as graphs from './graphs.js';
import * as structures from './structures.js';
import * as dp from './dp.js';
import {
  randomArray,
  randomArrayForRadix,
  randomFloatArray,
  parseNumberList,
  parseWordList,
  DEFAULT_GRAPH,
} from './core.js';
import { enrichStepsWithCodeSync } from './codeSync/index.js';
import { enrichAllSteps } from './stepSync.js';

export const ALGORITHM_CATEGORIES = {
  searching: 'Searching',
  sorting: 'Sorting',
  trees: 'Trees',
  graphs: 'Graphs',
  structures: 'Linear Structures',
  dp: 'Dynamic Programming',
  techniques: 'Techniques',
};

export const ALGORITHMS = [
  {
    id: 'linear-search',
    name: 'Linear Search',
    category: 'searching',
    renderer: 'array',
    inputType: 'array-target',
    defaultTarget: 42,
    generate: (input, config) => searching.linearSearch(input, config.target ?? 42),
    randomInput: () => randomArray(8),
  },
  {
    id: 'binary-search',
    name: 'Binary Search',
    category: 'searching',
    renderer: 'array',
    inputType: 'array-target',
    defaultTarget: 42,
    generate: (input, config) => searching.binarySearch(input, config.target ?? 42),
    randomInput: () => randomArray(10),
  },
  {
    id: 'jump-search',
    name: 'Jump Search',
    category: 'searching',
    renderer: 'array',
    inputType: 'array-target',
    defaultTarget: 42,
    generate: (input, config) => searching.jumpSearch(input, config.target ?? 42),
    randomInput: () => randomArray(12),
  },
  {
    id: 'interpolation-search',
    name: 'Interpolation Search',
    category: 'searching',
    renderer: 'array',
    inputType: 'array-target',
    defaultTarget: 42,
    generate: (input, config) => searching.interpolationSearch(input, config.target ?? 42),
    randomInput: () => randomArray(12),
  },
  {
    id: 'bubble-sort',
    name: 'Bubble Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.bubbleSort(input),
    randomInput: () => randomArray(8),
  },
  {
    id: 'selection-sort',
    name: 'Selection Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.selectionSort(input),
    randomInput: () => randomArray(8),
  },
  {
    id: 'insertion-sort',
    name: 'Insertion Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.insertionSort(input),
    randomInput: () => randomArray(8),
  },
  {
    id: 'merge-sort',
    name: 'Merge Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.mergeSort(input),
    randomInput: () => randomArray(8),
  },
  {
    id: 'quick-sort',
    name: 'Quick Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.quickSort(input),
    randomInput: () => randomArray(8),
  },
  {
    id: 'heap-sort',
    name: 'Heap Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.heapSort(input),
    randomInput: () => randomArray(8),
  },
  {
    id: 'counting-sort',
    name: 'Counting Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.countingSort(input),
    randomInput: () => randomArray(10, 0, 20),
  },
  {
    id: 'radix-sort',
    name: 'Radix Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.radixSort(input),
    randomInput: () => randomArrayForRadix(8),
  },
  {
    id: 'bucket-sort',
    name: 'Bucket Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.bucketSort(input),
    randomInput: () => randomFloatArray(8),
  },
  {
    id: 'shell-sort',
    name: 'Shell Sort',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.shellSort(input),
    randomInput: () => randomArray(10),
  },
  {
    id: 'bst-insert',
    name: 'Binary Search Tree',
    category: 'trees',
    renderer: 'tree',
    inputType: 'array',
    generate: (input) => trees.bstInsert(input),
    randomInput: () => [50, 30, 70, 20, 40, 60, 80],
  },
  {
    id: 'avl-insert',
    name: 'AVL Tree',
    category: 'trees',
    renderer: 'tree',
    inputType: 'array',
    generate: (input) => trees.avlInsert(input),
    randomInput: () => [30, 20, 40, 10, 25, 35, 50],
  },
  {
    id: 'trie-insert',
    name: 'Trie',
    category: 'trees',
    renderer: 'tree',
    inputType: 'words',
    generate: (input) => trees.trieInsert(input),
    randomInput: () => ['cat', 'car', 'card', 'care', 'dog'],
  },
  {
    id: 'heapify',
    name: 'Binary Heap',
    category: 'trees',
    renderer: 'tree',
    inputType: 'array',
    generate: (input) => trees.heapifyVisual(input),
    randomInput: () => [40, 30, 50, 20, 35, 45, 10],
  },
  {
    id: 'dfs',
    name: 'Depth-First Search',
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: (input, config) => graphs.dfs({ start: config.start ?? DEFAULT_GRAPH.start }),
    randomInput: () => [],
  },
  {
    id: 'bfs',
    name: 'Breadth-First Search',
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: (input, config) => graphs.bfs({ start: config.start ?? DEFAULT_GRAPH.start }),
    randomInput: () => [],
  },
  {
    id: 'dijkstra',
    name: "Dijkstra's Algorithm",
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: (input, config) => graphs.dijkstra({ start: config.start ?? DEFAULT_GRAPH.start }),
    randomInput: () => [],
  },
  {
    id: 'bellman-ford',
    name: 'Bellman-Ford',
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: () => graphs.bellmanFord(),
    randomInput: () => [],
  },
  {
    id: 'floyd-warshall',
    name: 'Floyd-Warshall',
    category: 'graphs',
    renderer: 'matrix',
    inputType: 'graph',
    generate: () => graphs.floydWarshall(),
    randomInput: () => [],
  },
  {
    id: 'prim',
    name: "Prim's MST",
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: () => graphs.prim(),
    randomInput: () => [],
  },
  {
    id: 'kruskal',
    name: "Kruskal's MST",
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: () => graphs.kruskal(),
    randomInput: () => [],
  },
  {
    id: 'a-star',
    name: 'A* Search',
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: (input, config) =>
      graphs.astar({ start: config.start ?? DEFAULT_GRAPH.start, goal: config.goal ?? DEFAULT_GRAPH.goal }),
    randomInput: () => [],
  },
  {
    id: 'stack-operations',
    name: 'Stack Operations',
    category: 'structures',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.stackOperations(input),
    randomInput: () => [1, 2, 3, 4],
  },
  {
    id: 'queue-operations',
    name: 'Queue Operations',
    category: 'structures',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.queueOperations(input),
    randomInput: () => [10, 20, 30],
  },
  {
    id: 'linked-list-insert',
    name: 'Linked List Insert',
    category: 'structures',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.linkedListInsert(input),
    randomInput: () => [5, 10, 15, 20],
  },
  {
    id: 'two-pointer',
    name: 'Two Pointer Technique',
    category: 'techniques',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.twoPointerScan(input),
    randomInput: () => randomArray(8),
  },
  {
    id: 'sliding-window',
    name: 'Sliding Window',
    category: 'techniques',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.slidingWindow(input),
    randomInput: () => [1, 3, -1, -3, 5, 3, 6, 7],
  },
  {
    id: 'prefix-sum',
    name: 'Prefix Sum',
    category: 'techniques',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.prefixSum(input),
    randomInput: () => randomArray(6),
  },
  {
    id: 'fibonacci-dp',
    name: 'Fibonacci (Memoization)',
    category: 'dp',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => dp.fibonacciMemo(input),
    randomInput: () => [8],
  },
  {
    id: 'knapsack-dp',
    name: '0/1 Knapsack',
    category: 'dp',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => dp.knapsackDP(input),
    randomInput: () => [1, 2, 3, 6, 10, 12],
  },
  {
    id: 'coin-change-dp',
    name: 'Coin Change',
    category: 'dp',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => dp.coinChangeDP(input),
    randomInput: () => [1, 2, 5],
  },
  {
    id: 'lis-dp',
    name: 'Longest Increasing Subsequence',
    category: 'dp',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => dp.lisDP(input),
    randomInput: () => randomArray(8),
  },
  {
    id: 'ternary-search',
    name: 'Ternary Search',
    category: 'searching',
    renderer: 'array',
    inputType: 'array-target',
    defaultTarget: 42,
    generate: (input, config) => searching.ternarySearch(input, config.target ?? 42),
    randomInput: () => randomArray(12),
  },
  {
    id: 'exponential-search',
    name: 'Exponential Search',
    category: 'searching',
    renderer: 'array',
    inputType: 'array-target',
    defaultTarget: 42,
    generate: (input, config) => searching.exponentialSearch(input, config.target ?? 42),
    randomInput: () => randomArray(16),
  },
  {
    id: 'tim-sort',
    name: 'Tim Sort (demo)',
    category: 'sorting',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => sorting.timSort(input),
    randomInput: () => randomArray(10),
  },
  {
    id: 'tree-inorder',
    name: 'Inorder Traversal',
    category: 'trees',
    renderer: 'tree',
    inputType: 'array',
    generate: (input) => trees.treeInorder(input),
    randomInput: () => [50, 30, 70, 20, 40],
  },
  {
    id: 'tree-preorder',
    name: 'Preorder Traversal',
    category: 'trees',
    renderer: 'tree',
    inputType: 'array',
    generate: (input) => trees.treePreorder(input),
    randomInput: () => [40, 20, 60, 10, 30],
  },
  {
    id: 'tree-postorder',
    name: 'Postorder Traversal',
    category: 'trees',
    renderer: 'tree',
    inputType: 'array',
    generate: (input) => trees.treePostorder(input),
    randomInput: () => [30, 20, 40, 10, 25],
  },
  {
    id: 'level-order-bfs',
    name: 'Level Order Traversal',
    category: 'trees',
    renderer: 'tree',
    inputType: 'array',
    generate: (input) => trees.levelOrderTraversal(input),
    randomInput: () => [40, 30, 50, 20, 35],
  },
  {
    id: 'topological-sort',
    name: 'Topological Sort',
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: () => graphs.topologicalSort(),
    randomInput: () => [],
  },
  {
    id: 'union-find',
    name: 'Union Find',
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: () => graphs.unionFind(),
    randomInput: () => [],
  },
  {
    id: 'scc-kosaraju',
    name: 'Strongly Connected Components',
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: () => graphs.kosarajuSCC(),
    randomInput: () => [],
  },
  {
    id: 'bridges-tarjan',
    name: 'Bridges in Graph',
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: () => graphs.tarjanBridges(),
    randomInput: () => [],
  },
  {
    id: 'articulation-points',
    name: 'Articulation Points',
    category: 'graphs',
    renderer: 'graph',
    inputType: 'graph',
    generate: () => graphs.tarjanArticulationPoints(),
    randomInput: () => [],
  },
  {
    id: 'hash-linear-probing',
    name: 'Hash Table (Linear Probing)',
    category: 'structures',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.hashLinearProbing(input),
    randomInput: () => [3, 7, 2, 9, 5],
  },
  {
    id: 'monotonic-stack',
    name: 'Monotonic Stack',
    category: 'structures',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.monotonicStack(input),
    randomInput: () => [2, 1, 2, 4, 3],
  },
  {
    id: 'deque-sliding-window',
    name: 'Deque Sliding Window',
    category: 'structures',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.dequeSlidingWindowMax(input),
    randomInput: () => [1, 3, -1, -3, 5, 3, 6, 7],
  },
  {
    id: 'bitmask-dp',
    name: 'Bitmask DP (demo)',
    category: 'dp',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => dp.bitmaskDP(input),
    randomInput: () => [1, 2, 3, 6, 10, 12],
  },
  {
    id: 'edit-distance-dp',
    name: 'Edit Distance',
    category: 'dp',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => dp.editDistanceDP(input),
    randomInput: () => randomArray(6),
  },
  {
    id: 'greedy-activity',
    name: 'Activity Selection (Greedy)',
    category: 'techniques',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.greedyActivitySelection(input),
    randomInput: () => randomArray(8),
  },
  {
    id: 'backtracking-subsets',
    name: 'Backtracking Subsets',
    category: 'techniques',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.backtrackingSubsets(input),
    randomInput: () => [1, 2, 3],
  },
  {
    id: 'kmp-search',
    name: 'KMP Pattern Match (demo)',
    category: 'techniques',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.kmpSearch(input),
    randomInput: () => randomArray(10),
  },
  {
    id: 'rabin-karp',
    name: 'Rabin-Karp (demo)',
    category: 'techniques',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.rabinKarp(input),
    randomInput: () => randomArray(10),
  },
  {
    id: 'segment-tree-demo',
    name: 'Segment Tree Range Query',
    category: 'trees',
    renderer: 'tree',
    inputType: 'array',
    generate: (input) => trees.segmentTreeDemo(input),
    randomInput: () => [1, 3, 5, 7, 9, 11],
  },
  {
    id: 'fenwick-tree-demo',
    name: 'Fenwick Tree',
    category: 'trees',
    renderer: 'array',
    inputType: 'array',
    generate: (input) => structures.fenwickTree(input),
    randomInput: () => randomArray(8),
  },
];

export const ALGORITHM_MAP = Object.fromEntries(ALGORITHMS.map((algo) => [algo.id, algo]));

export const TOPIC_ALGORITHM_MAP = {
  arrays: 'bubble-sort',
  strings: 'linear-search',
  searching: 'binary-search',
  sorting: 'merge-sort',
  recursion: 'quick-sort',
  'linked-lists': 'insertion-sort',
  stacks: 'insertion-sort',
  queues: 'bfs',
  deques: 'shell-sort',
  'hash-tables': 'linear-search',
  heaps: 'heapify',
  'priority-queues': 'heap-sort',
  trees: 'bst-insert',
  'binary-search-trees': 'bst-insert',
  'avl-trees': 'avl-insert',
  'red-black-trees': 'avl-insert',
  trie: 'trie-insert',
  graphs: 'dfs',
  'dynamic-programming': 'floyd-warshall',
  greedy: 'kruskal',
  backtracking: 'dfs',
  'bit-manipulation': 'counting-sort',
};

export const resolveAlgorithmId = (slugOrId) => {
  if (ALGORITHM_MAP[slugOrId]) return slugOrId;
  return TOPIC_ALGORITHM_MAP[slugOrId] ?? null;
};

export const runAlgorithm = (algorithmId, rawInput, config = {}) => {
  const algo = ALGORITHM_MAP[algorithmId];
  if (!algo) throw new Error(`Unknown algorithm: ${algorithmId}`);

  let input = rawInput;
  if (algo.inputType === 'array') {
    input = parseNumberList(typeof rawInput === 'string' ? rawInput : rawInput?.join(','), algo.randomInput());
  } else if (algo.inputType === 'array-target') {
    input = parseNumberList(typeof rawInput === 'string' ? rawInput : rawInput?.join(','), algo.randomInput());
  } else if (algo.inputType === 'words') {
    input = parseWordList(typeof rawInput === 'string' ? rawInput : rawInput?.join(','), algo.randomInput());
  }

  const rawSteps = algo.generate(input, config);
  const syncedSteps = enrichStepsWithCodeSync(algo.id, algo.category, rawSteps);
  const steps = enrichAllSteps(syncedSteps, algo.id, algo.category, config, algo.name);
  return { algorithm: algo, input, steps };
};

export default {
  ALGORITHMS,
  ALGORITHM_MAP,
  ALGORITHM_CATEGORIES,
  TOPIC_ALGORITHM_MAP,
  resolveAlgorithmId,
  runAlgorithm,
};
