import { TOPIC_CATEGORIES, DIFFICULTY } from 'shared/constants';

/**
 * 40 curriculum modules. Each module contains 12–13 lessons (Topics in the DB).
 * Lesson slugs: `{moduleId}-{lesson-slug}`.
 */
export const MODULES = [
  {
    id: 'intro-to-programming',
    title: 'Introduction to Programming',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'linear-search',
    lessons: [
      'What Is Programming',
      'Programs vs Algorithms',
      'Source Code and Compilation',
      'Interpreted vs Compiled Languages',
      'The Programming Workflow',
      'Debugging Mindset',
      'Reading Error Messages',
      'Using an IDE Effectively',
      'Version Control Basics',
      'Writing Pseudocode',
      'Problem Decomposition',
      'Computational Thinking',
      'Career Paths in Software',
      'Setting Up Your Learning Environment',
    ],
  },
  {
    id: 'programming-basics',
    title: 'Programming Basics',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'linear-search',
    lessons: [
      'Syntax and Semantics',
      'Statements and Expressions',
      'Code Blocks and Scope Preview',
      'Comments and Documentation',
      'Naming Conventions',
      'Code Style and Readability',
      'Constants and Immutability',
      'Type Coercion Overview',
      'Standard Input Output Flow',
      'Building a First Program',
      'Common Syntax Errors',
      'Testing Small Programs',
      'Refactoring Basics',
      'Reading Documentation Effectively',
    ],
  },
  {
    id: 'variables-data-types',
    title: 'Variables and Data Types',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'linear-search',
    lessons: [
      'What Is a Variable',
      'Declaration and Initialization',
      'Primitive Types Overview',
      'Integers and Floating Point',
      'Characters and Booleans',
      'Type Casting and Conversion',
      'Variable Scope Rules',
      'Lifetime and Storage Duration',
      'Constants and Literals',
      'Type Inference',
      'Strong vs Weak Typing',
      'Choosing Appropriate Types',
      'Type Safety in Practice',
    ],
  },
  {
    id: 'operators-expressions',
    title: 'Operators and Expressions',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'linear-search',
    lessons: [
      'Arithmetic Operators',
      'Relational Operators',
      'Logical Operators',
      'Bitwise Operators Intro',
      'Assignment Operators',
      'Operator Precedence',
      'Short Circuit Evaluation',
      'Increment and Decrement',
      'Ternary Conditional Operator',
      'Expression Evaluation Order',
      'Overflow and Underflow',
      'Writing Safe Expressions',
      'Numeric Precision and Rounding',
    ],
  },
  {
    id: 'input-output',
    title: 'Input and Output',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'linear-search',
    lessons: [
      'Standard Input Streams',
      'Standard Output Streams',
      'Formatted Output',
      'Reading Multiple Values',
      'File I O Basics',
      'Buffering and Flushing',
      'Parsing Input Safely',
      'Handling Invalid Input',
      'Competitive Programming I O',
      'JSON and Structured Data',
      'Logging vs Printing',
      'I O Performance Considerations',
      'Cross Platform I O Differences',
    ],
  },
  {
    id: 'conditionals',
    title: 'Conditionals',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'binary-search',
    lessons: [
      'Boolean Logic Foundations',
      'If Else Statements',
      'Else If Chains',
      'Switch Case Statements',
      'Nested Conditionals',
      'Guard Clauses',
      'Comparing Floating Point Values',
      'Range Checks and Boundaries',
      'Decision Tables',
      'Conditional Expressions',
      'Avoiding Deep Nesting',
      'Testing Branch Coverage',
      'Refactoring Conditional Logic',
    ],
  },
  {
    id: 'loops',
    title: 'Loops',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'linear-search',
    lessons: [
      'Why Loops Matter',
      'While Loops',
      'Do While Loops',
      'For Loops',
      'Enhanced For Each Loops',
      'Loop Invariants',
      'Break and Continue',
      'Nested Loops',
      'Infinite Loops and Prevention',
      'Loop Complexity Preview',
      'Choosing the Right Loop',
      'Translating Loops to Recursion',
      'Loop Optimization Patterns',
    ],
  },
  {
    id: 'functions',
    title: 'Functions',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'merge-sort',
    lessons: [
      'Functions as Abstraction',
      'Parameters and Arguments',
      'Return Values',
      'Pass by Value vs Reference',
      'Function Overloading',
      'Default Parameters',
      'Pure vs Impure Functions',
      'Higher Order Functions Intro',
      'Lambda and Anonymous Functions',
      'Recursion Preview in Functions',
      'Modular Program Design',
      'Testing Functions',
      'Documenting Function Contracts',
    ],
  },
  {
    id: 'recursion-fundamentals',
    title: 'Recursion Fundamentals',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'quick-sort',
    lessons: [
      'Base Case and Recursive Case',
      'Call Stack Visualization',
      'Factorial and Fibonacci',
      'Tail Recursion',
      'Mutual Recursion',
      'Recursion Tree Analysis',
      'When Recursion Fails',
      'Converting Recursion to Iteration',
      'Divide and Conquer Preview',
      'Backtracking Preview',
      'Memoization Preview',
      'Debugging Recursive Programs',
      'Recursion vs Iteration Tradeoffs',
    ],
  },
  {
    id: 'memory-pointers',
    title: 'Memory and Pointers',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'linear-search',
    lessons: [
      'Memory Hierarchy Overview',
      'Stack vs Heap Memory',
      'Pointers in C and C++',
      'References in C++ and Java',
      'Dynamic Memory Allocation',
      'Memory Leaks and Dangling Pointers',
      'Garbage Collection Models',
      'Pointer Arithmetic',
      'Smart Pointers Overview',
      'Memory Alignment',
      'Cache Locality',
      'Memory Safety Best Practices',
      'Valgrind and Memory Debuggers',
    ],
  },
  {
    id: 'arrays-fundamentals',
    title: 'Arrays Fundamentals',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'bubble-sort',
    lessons: [
      'Array Memory Layout',
      'Static vs Dynamic Arrays',
      'Indexing and Bounds',
      'Array Traversal Patterns',
      'In Place Modifications',
      'Multidimensional Arrays Intro',
      'Array Copying and Slicing',
      'Rotating Array Elements',
      'Frequency Counting with Arrays',
      'Prefix Sum Introduction',
      'Array Interview Patterns',
      'Common Array Pitfalls',
      'Array Algorithm Patterns Summary',
    ],
  },
  {
    id: 'strings-fundamentals',
    title: 'Strings Fundamentals',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'linear-search',
    lessons: [
      'String Representation',
      'Immutable vs Mutable Strings',
      'Character Encoding ASCII Unicode',
      'String Comparison',
      'Substring Operations',
      'String Builder Patterns',
      'Parsing and Tokenization',
      'Regular Expressions Intro',
      'Palindrome Techniques',
      'Anagram Detection',
      'String Matching Overview',
      'String Complexity Analysis',
      'Unicode and Internationalization',
    ],
  },
  {
    id: 'matrices',
    title: 'Matrices',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'floyd-warshall',
    lessons: [
      'Matrix Representation',
      'Row Major vs Column Major',
      'Matrix Traversal',
      'Matrix Transpose',
      'Matrix Multiplication Basics',
      'Spiral Matrix Traversal',
      'Diagonal Operations',
      'Search in Sorted Matrix',
      'Graph Adjacency Matrix',
      'Image Processing Grids',
      'Matrix DP Preview',
      'Matrix Space Optimization',
      'Sparse Matrix Representations',
    ],
  },
  {
    id: 'complexity-analysis',
    title: 'Complexity Analysis',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'merge-sort',
    lessons: [
      'Why Complexity Matters',
      'Counting Operations',
      'Big O Notation',
      'Big Omega Notation',
      'Big Theta Notation',
      'Best Average Worst Case',
      'Space Complexity',
      'Amortized Analysis Intro',
      'Master Theorem Overview',
      'Analyzing Recursive Algorithms',
      'Comparing Growth Rates',
      'Complexity in Interviews',
      'Profiling and Benchmarking Tools',
    ],
  },
  {
    id: 'searching-algorithms',
    title: 'Searching Algorithms',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'binary-search',
    lessons: [
      'Linear Search',
      'Binary Search on Arrays',
      'Binary Search on Answer',
      'Ternary Search',
      'Jump Search',
      'Interpolation Search',
      'Exponential Search',
      'Search in Rotated Arrays',
      'Search in 2D Matrices',
      'Lower and Upper Bound',
      'Search Space Reduction',
      'Searching Interview Patterns',
      'Search in Infinite Arrays',
    ],
  },
  {
    id: 'sorting-algorithms',
    title: 'Sorting Algorithms',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'merge-sort',
    lessons: [
      'Sorting Problem Definition',
      'Bubble Sort Analysis',
      'Selection Sort Analysis',
      'Insertion Sort Analysis',
      'Merge Sort Deep Dive',
      'Quick Sort Deep Dive',
      'Heap Sort Overview',
      'Counting Sort',
      'Radix Sort',
      'Stable vs Unstable Sort',
      'Custom Comparators',
      'Sorting Interview Patterns',
      'External Sorting Overview',
    ],
  },
  {
    id: 'bit-manipulation',
    title: 'Bit Manipulation',
    category: TOPIC_CATEGORIES.ADVANCED,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'counting-sort',
    lessons: [
      'Binary Number System',
      'Bitwise AND OR XOR NOT',
      'Left and Right Shifts',
      'Setting Clearing Toggling Bits',
      'Count Set Bits',
      'Power of Two Check',
      'Single Number XOR Trick',
      'Bitmask Subsets',
      'Bit Manipulation in DP',
      'Endianness',
      'Bit Tricks for Interviews',
      'Bit Manipulation Pitfalls',
    ],
  },
  {
    id: 'hashing-fundamentals',
    title: 'Hashing Fundamentals',
    category: TOPIC_CATEGORIES.LINEAR,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'linear-search',
    lessons: [
      'Hash Function Properties',
      'Collision Resolution Chaining',
      'Collision Resolution Open Addressing',
      'Load Factor and Rehashing',
      'Universal Hashing',
      'Rolling Hash',
      'Hash Maps in Practice',
      'Hash Sets in Practice',
      'Frequency Maps',
      'Two Sum with Hashing',
      'Consistent Hashing Intro',
      'Hashing Security Overview',
    ],
  },
  {
    id: 'two-pointer-sliding-window',
    title: 'Two Pointer and Sliding Window',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'shell-sort',
    lessons: [
      'Opposite Direction Two Pointer',
      'Same Direction Two Pointer',
      'Fast and Slow Pointers',
      'Fixed Size Sliding Window',
      'Variable Size Sliding Window',
      'Window with Hash Map',
      'Longest Substring Without Repeat',
      'Minimum Window Substring',
      'Subarray Sum Equals K',
      'Container With Most Water',
      'Trapping Rain Water',
      'Two Pointer Interview Patterns',
    ],
  },
  {
    id: 'prefix-sum-binary-search',
    title: 'Prefix Sum and Binary Search',
    category: TOPIC_CATEGORIES.FUNDAMENTALS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'binary-search',
    lessons: [
      'Building Prefix Sum Arrays',
      'Range Sum Queries',
      'Prefix Sum with Hash Map',
      'Difference Arrays',
      '2D Prefix Sum',
      'Binary Search on Prefix',
      'Lower Bound Implementation',
      'Upper Bound Implementation',
      'Binary Search on Functions',
      'Parametric Search',
      'Koko Eating Bananas Pattern',
      'Ship Packages Pattern',
    ],
  },
  {
    id: 'greedy-techniques',
    title: 'Greedy Techniques',
    category: TOPIC_CATEGORIES.ADVANCED,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'kruskal',
    lessons: [
      'Greedy Choice Property',
      'Proving Greedy Correctness',
      'Activity Selection',
      'Interval Scheduling',
      'Huffman Coding Overview',
      'Fractional Knapsack',
      'Coin Change Greedy Cases',
      'Minimum Platforms',
      'Jump Game Greedy',
      'Task Scheduler Greedy',
      'When Greedy Fails',
      'Greedy vs Dynamic Programming',
    ],
  },
  {
    id: 'divide-and-conquer',
    title: 'Divide and Conquer',
    category: TOPIC_CATEGORIES.ADVANCED,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'merge-sort',
    lessons: [
      'Divide Conquer Framework',
      'Merge Sort as D and C',
      'Quick Sort as D and C',
      'Binary Search as D and C',
      'Maximum Subarray Divide Conquer',
      'Closest Pair of Points',
      'Strassen Matrix Multiplication',
      'Karatsuba Multiplication',
      'Master Theorem Applications',
      'Combining Subproblem Results',
      'Parallel Divide and Conquer',
      'D and C Interview Patterns',
    ],
  },
  {
    id: 'backtracking',
    title: 'Backtracking',
    category: TOPIC_CATEGORIES.ADVANCED,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'dfs',
    lessons: [
      'Backtracking Template',
      'Subsets Generation',
      'Permutations Generation',
      'Combinations Generation',
      'N Queens Problem',
      'Sudoku Solver',
      'Word Search Grid',
      'Palindrome Partitioning',
      'Constraint Propagation',
      'Pruning Strategies',
      'Branch and Bound Intro',
      'Backtracking Complexity',
    ],
  },
  {
    id: 'dynamic-programming',
    title: 'Dynamic Programming',
    category: TOPIC_CATEGORIES.ADVANCED,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'floyd-warshall',
    lessons: [
      'Overlapping Subproblems',
      'Optimal Substructure',
      'Top Down Memoization',
      'Bottom Up Tabulation',
      '1D DP Patterns',
      '2D DP Patterns',
      'Knapsack Variants',
      'Longest Common Subsequence',
      'Longest Increasing Subsequence',
      'Edit Distance',
      'Bitmask DP Intro',
      'DP Space Optimization',
    ],
  },
  {
    id: 'linked-lists',
    title: 'Linked Lists',
    category: TOPIC_CATEGORIES.LINEAR,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'insertion-sort',
    lessons: [
      'Singly Linked List Structure',
      'Doubly Linked List Structure',
      'Circular Linked List',
      'Insert at Head and Tail',
      'Delete Node Operations',
      'Reverse Linked List',
      'Detect Cycle Floyd',
      'Find Middle Node',
      'Merge Two Sorted Lists',
      'Remove Nth From End',
      'LRU Cache Design',
      'Linked List Interview Patterns',
    ],
  },
  {
    id: 'stacks-queues',
    title: 'Stacks and Queues',
    category: TOPIC_CATEGORIES.LINEAR,
    difficulty: DIFFICULTY.BEGINNER,
    visualizerId: 'insertion-sort',
    lessons: [
      'Stack ADT Operations',
      'Queue ADT Operations',
      'Deque Operations',
      'Implement Stack with Array',
      'Implement Queue with Linked List',
      'Valid Parentheses Pattern',
      'Monotonic Stack',
      'Monotonic Queue',
      'Next Greater Element',
      'Sliding Window Maximum Queue',
      'BFS Queue Applications',
      'Stack Queue Interview Patterns',
    ],
  },
  {
    id: 'hash-tables-maps',
    title: 'Hash Tables and Maps',
    category: TOPIC_CATEGORIES.LINEAR,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'linear-search',
    lessons: [
      'Hash Table Internals',
      'HashMap API Patterns',
      'HashSet API Patterns',
      'Frequency Counting',
      'Group Anagrams',
      'Subarray Sum Hash Map',
      'LRU Cache Hash Map',
      'Design Hash Map',
      'Collision Handling Deep Dive',
      'Amortized O1 Operations',
      'Hash Map vs Tree Map',
      'Hash Table Interview Patterns',
    ],
  },
  {
    id: 'trees-fundamentals',
    title: 'Trees Fundamentals',
    category: TOPIC_CATEGORIES.TREES,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'bst-insert',
    lessons: [
      'Tree Terminology',
      'Binary Tree Properties',
      'Tree Traversals Inorder',
      'Tree Traversals Preorder',
      'Tree Traversals Postorder',
      'Level Order BFS Traversal',
      'Height and Depth',
      'Balanced vs Unbalanced',
      'Serialize Deserialize Tree',
      'Lowest Common Ancestor',
      'Diameter of Binary Tree',
      'Tree Interview Patterns',
    ],
  },
  {
    id: 'bst-balanced-trees',
    title: 'BST and Balanced Trees',
    category: TOPIC_CATEGORIES.TREES,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'avl-insert',
    lessons: [
      'Binary Search Tree Property',
      'BST Insert and Delete',
      'BST Search Complexity',
      'AVL Tree Rotations',
      'Red Black Tree Rules',
      'B Tree Overview',
      'B Plus Tree Overview',
      'Self Balancing Tradeoffs',
      'Order Statistics Tree',
      'Range Queries on BST',
      'Convert Sorted Array to BST',
      'Balanced Tree Interview Patterns',
    ],
  },
  {
    id: 'heap-priority-queue',
    title: 'Heap and Priority Queue',
    category: TOPIC_CATEGORIES.LINEAR,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'heapify',
    lessons: [
      'Complete Binary Tree Property',
      'Min Heap Operations',
      'Max Heap Operations',
      'Heapify Build Heap',
      'Priority Queue ADT',
      'Heap Sort Connection',
      'Kth Largest with Heap',
      'Merge K Sorted Lists',
      'Dijkstra with Priority Queue',
      'Median from Data Stream',
      'Indexed Priority Queue',
      'Heap Interview Patterns',
    ],
  },
  {
    id: 'trie-segment-fenwick',
    title: 'Trie Segment and Fenwick Trees',
    category: TOPIC_CATEGORIES.TREES,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'trie-insert',
    lessons: [
      'Trie Node Structure',
      'Trie Insert Search Delete',
      'Prefix Matching Applications',
      'Word Search with Trie',
      'Segment Tree Build',
      'Segment Tree Range Query',
      'Segment Tree Range Update',
      'Lazy Propagation',
      'Fenwick Tree Basics',
      'Fenwick Range Updates',
      '2D Segment Tree Intro',
      'Advanced Tree Interview Patterns',
    ],
  },
  {
    id: 'union-find',
    title: 'Union Find',
    category: TOPIC_CATEGORIES.GRAPHS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'kruskal',
    lessons: [
      'Disjoint Set Union Concept',
      'Union Find with Array',
      'Path Compression',
      'Union by Rank',
      'Connected Components',
      'Detect Cycle in Graph',
      'Kruskal MST with Union Find',
      'Number of Islands Union Find',
      'Dynamic Connectivity',
      'Offline Queries with DSU',
      'Union Find Complexity',
      'Union Find Interview Patterns',
    ],
  },
  {
    id: 'graphs-fundamentals',
    title: 'Graphs Fundamentals',
    category: TOPIC_CATEGORIES.GRAPHS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'dfs',
    lessons: [
      'Graph Terminology',
      'Directed vs Undirected',
      'Weighted Graphs',
      'Adjacency List Representation',
      'Adjacency Matrix Representation',
      'Degree and Handshaking Lemma',
      'DAG Properties',
      'Graph Modeling Problems',
      'Bipartite Graph Check',
      'Cycle Detection Overview',
      'Graph Complexity Basics',
      'Graph Interview Foundations',
    ],
  },
  {
    id: 'graph-traversal',
    title: 'Graph Traversal',
    category: TOPIC_CATEGORIES.GRAPHS,
    difficulty: DIFFICULTY.INTERMEDIATE,
    visualizerId: 'bfs',
    lessons: [
      'Depth First Search',
      'Breadth First Search',
      'DFS vs BFS Comparison',
      'Topological Sort Kahn',
      'Topological Sort DFS',
      'Connected Components DFS',
      'BFS Shortest Path Unweighted',
      'Multi Source BFS',
      '0 1 BFS',
      'Strongly Connected Components',
      'Bridges in Graph',
      'Articulation Points',
    ],
  },
  {
    id: 'shortest-path-algorithms',
    title: 'Shortest Path Algorithms',
    category: TOPIC_CATEGORIES.GRAPHS,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'dijkstra',
    lessons: [
      'Single Source Shortest Path',
      'Dijkstra Algorithm',
      'Bellman Ford Algorithm',
      'Floyd Warshall Algorithm',
      'SPFA Algorithm',
      'Shortest Path in DAG',
      'A Star Search',
      'Bidirectional Search',
      'Shortest Path with Constraints',
      'Negative Cycle Detection',
      'Path Reconstruction',
      'Shortest Path Interview Patterns',
    ],
  },
  {
    id: 'mst-graph-advanced',
    title: 'MST and Advanced Graphs',
    category: TOPIC_CATEGORIES.GRAPHS,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'prim',
    lessons: [
      'Minimum Spanning Tree Definition',
      'Prim Algorithm',
      'Kruskal Algorithm',
      'MST Cut Property',
      'Maximum Spanning Tree',
      'Second Best MST',
      'Minimum Bottleneck Spanning Tree',
      'Network Flow Intro',
      'Bipartite Matching Intro',
      'Euler Path and Circuit',
      'Hamilton Path Intro',
      'Advanced Graph Interview Patterns',
    ],
  },
  {
    id: 'string-algorithms-advanced',
    title: 'Advanced String Algorithms',
    category: TOPIC_CATEGORIES.ADVANCED,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'trie-insert',
    lessons: [
      'Naive String Matching',
      'KMP Algorithm',
      'Rabin Karp Rolling Hash',
      'Z Algorithm',
      'Trie Pattern Matching',
      'Suffix Array Construction',
      'Suffix Tree Overview',
      'Longest Palindromic Substring',
      'Longest Repeating Substring',
      'Aho Corasick Intro',
      'String Hashing Pitfalls',
      'String Algorithm Interviews',
    ],
  },
  {
    id: 'number-theory-math',
    title: 'Number Theory and Math',
    category: TOPIC_CATEGORIES.ADVANCED,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'counting-sort',
    lessons: [
      'Modular Arithmetic',
      'GCD and Euclidean Algorithm',
      'LCM Properties',
      'Prime Number Tests',
      'Sieve of Eratosthenes',
      'Fast Exponentiation',
      'Matrix Exponentiation',
      'Combinatorics Basics',
      'Inclusion Exclusion',
      'Fermat Little Theorem',
      'Chinese Remainder Theorem Intro',
      'Math for Competitive Programming',
    ],
  },
  {
    id: 'game-theory-geometry',
    title: 'Game Theory and Geometry',
    category: TOPIC_CATEGORIES.ADVANCED,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'dfs',
    lessons: [
      'Game Theory Basics',
      'Nim Game Analysis',
      'Grundy Numbers Intro',
      'Minimax Algorithm',
      'Alpha Beta Pruning',
      'Computational Geometry Points',
      'Cross Product and Orientation',
      'Convex Hull Intro',
      'Line Intersection',
      'Closest Pair Geometry',
      'Sweep Line Algorithms',
      'Advanced Math Interview Topics',
    ],
  },
  {
    id: 'interview-prep-mastery',
    title: 'Interview Preparation Mastery',
    category: TOPIC_CATEGORIES.ADVANCED,
    difficulty: DIFFICULTY.ADVANCED,
    visualizerId: 'binary-search',
    lessons: [
      'Interview Problem Solving Framework',
      'Communicating Your Approach',
      'Analyzing Constraints Quickly',
      'Pattern Recognition Guide',
      'Mock Interview Strategies',
      'Behavioral Questions for Engineers',
      'System Design Bridge Topics',
      'FAANG Style Problem Sets',
      'Startup Interview Expectations',
      'Offer Negotiation for New Grads',
      'Building a Study Schedule',
      'Final Review Checklist',
      'Day Before Interview Plan',
      'Post Interview Reflection',
    ],
  },
];

export default MODULES;
